runtime: python39  # Use Python 3.9 runtime
entrypoint: python Deploy_Newsapp.py  # Command to run your app

# Optional: Instance class for resource allocation
instance_class: F2

# Optional: Define environment variables
env_variables:
  OPENAI_API_KEY: "your-api-key"
  DATABASE_URL: "your-database-url"

# Optional: Static file handler (if serving files)
handlers:
  - url: /static
    static_dir: static
  - url: /.*
    script: auto
